.PHONY: default build clean docs pretty lint test run

default: clean build

build:
	@echo "Nothing to build."

clean:
	@echo "Nothing to clean."

docs:
	@echo "This project has no documentation."

pretty:
	@echo "Already pretty."

lint:
	@echo "Nothing to check."

test:
	@echo "This project has no tests."
