name: Changelog

on:
  workflow_call:
    inputs:
      automatic-release-tag:
        description: The automatic release tag we're maintaining.
        required: false
        type: string
    outputs:
      automatic-releases-tag:
        description: The release tag this action just processed.
        value: ${{ jobs.changelog.outputs.automatic-releases-tag }}
      commits-total:
        description: Total amount of commits since last release.
        value: ${{ jobs.changelog.outputs.commits-total }}
      unconventional-total:
        description: Total amount of commits without convention.
        value: ${{ jobs.changelog.outputs.unconventional-total }}
      lifecycle-total:
        description: Total amount of commits that fall into the "lifecycle" category.
        value: ${{ jobs.changelog.outputs.lifecycle-total }}
      major-total:
        description: Total amount of commits that fall into the "major change" category.
        value: ${{ jobs.changelog.outputs.major-total }}
      minor-total:
        description: Total amount of commits that fall into the "minor change" category.
        value: ${{ jobs.changelog.outputs.minor-total }}
      patch-total:
        description: Total amount of commits that fall into the "patch change" category.
        value: ${{ jobs.changelog.outputs.patch-total }}
      upload-url:
        description: The URL for uploading additional assets to the release.
        value: ${{ jobs.changelog.outputs.upload-url }}

      version-current:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-current }}
      version-dev:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-dev }}
      version-dev-extended:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-dev-extended }}
      version-dev-extended-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-dev-extended-hash }}
      version-dev-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-dev-hash }}
      version-extension:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-extension }}
      version-major:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-major }}
      version-major-dev:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-major-dev }}
      version-major-dev-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-major-dev-hash }}
      version-major-extended-dev:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-major-extended-dev }}
      version-major-extended-dev-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-major-extended-dev-hash }}
      version-major-extended-nightly:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-major-extended-nightly }}
      version-major-extended-nightly-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-major-extended-nightly-hash }}
      version-major-nightly:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-major-nightly }}
      version-major-nightly-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-major-nightly-hash }}
      version-minor:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-minor }}
      version-minor-dev:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-minor-dev }}
      version-minor-dev-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-minor-dev-hash }}
      version-minor-extended-dev:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-minor-extended-dev }}
      version-minor-extended-dev-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-minor-extended-dev-hash }}
      version-minor-extended-nightly:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-minor-extended-nightly }}
      version-minor-extended-nightly-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-minor-extended-nightly-hash }}
      version-minor-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-minor-hash }}
      version-minor-nightly:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-minor-nightly }}
      version-minor-nightly-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-minor-nightly-hash }}
      version-nightly:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-nightly }}
      version-nightly-extended:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-nightly-extended }}
      version-nightly-extended-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-nightly-extended-hash }}
      version-nightly-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-nightly-hash }}
      version-patch:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-patch }}
      version-patch-dev:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-patch-dev }}
      version-patch-dev-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-patch-dev-hash }}
      version-patch-extended-dev:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-patch-extended-dev }}
      version-patch-extended-dev-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-patch-extended-dev-hash }}
      version-patch-extended-nightly:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-patch-extended-nightly }}
      version-patch-extended-nightly-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-patch-extended-nightly-hash }}
      version-patch-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-patch-hash }}
      version-patch-nightly:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-patch-nightly }}
      version-patch-nightly-hash:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-patch-nightly-hash }}
      version-root:
        description: Version suggestion
        value: ${{ jobs.changelog.outputs.version-root }}

jobs:
  changelog:
    name: Build
    outputs:
      automatic-releases-tag: ${{ steps.changelog.outputs.automatic-releases-tag }}
      commits-total: ${{ steps.changelog.outputs.commits-total }}
      unconventional-total: ${{ steps.changelog.outputs.unconventional-total }}
      lifecycle-total: ${{ steps.changelog.outputs.lifecycle-total }}
      major-total: ${{ steps.changelog.outputs.major-total }}
      minor-total: ${{ steps.changelog.outputs.minor-total }}
      patch-total: ${{ steps.changelog.outputs.patch-total }}
      upload-url: ${{ steps.changelog.outputs.upload-url }}

      version-current: ${{ steps.changelog.outputs.version-current }}
      version-dev: ${{ steps.changelog.outputs.version-dev }}
      version-dev-extended: ${{ steps.changelog.outputs.version-dev-extended }}
      version-dev-extended-hash: ${{ steps.changelog.outputs.version-dev-extended-hash }}
      version-dev-hash: ${{ steps.changelog.outputs.version-dev-hash }}
      version-extension: ${{ steps.changelog.outputs.version-extension }}
      version-major: ${{ steps.changelog.outputs.version-major }}
      version-major-dev: ${{ steps.changelog.outputs.version-major-dev }}
      version-major-dev-hash: ${{ steps.changelog.outputs.version-major-dev-hash }}
      version-major-extended-dev: ${{ steps.changelog.outputs.version-major-extended-dev }}
      version-major-extended-dev-hash: ${{ steps.changelog.outputs.version-major-extended-dev-hash }}
      version-major-extended-nightly: ${{ steps.changelog.outputs.version-major-extended-nightly }}
      version-major-extended-nightly-hash: ${{ steps.changelog.outputs.version-major-extended-nightly-hash }}
      version-major-nightly: ${{ steps.changelog.outputs.version-major-nightly }}
      version-major-nightly-hash: ${{ steps.changelog.outputs.version-major-nightly-hash }}
      version-minor: ${{ steps.changelog.outputs.version-minor }}
      version-minor-dev: ${{ steps.changelog.outputs.version-minor-dev }}
      version-minor-dev-hash: ${{ steps.changelog.outputs.version-minor-dev-hash }}
      version-minor-extended-dev: ${{ steps.changelog.outputs.version-minor-extended-dev }}
      version-minor-extended-dev-hash: ${{ steps.changelog.outputs.version-minor-extended-dev-hash }}
      version-minor-extended-nightly: ${{ steps.changelog.outputs.version-minor-extended-nightly }}
      version-minor-extended-nightly-hash: ${{ steps.changelog.outputs.version-minor-extended-nightly-hash }}
      version-minor-hash: ${{ steps.changelog.outputs.version-minor-hash }}
      version-minor-nightly: ${{ steps.changelog.outputs.version-minor-nightly }}
      version-minor-nightly-hash: ${{ steps.changelog.outputs.version-minor-nightly-hash }}
      version-nightly: ${{ steps.changelog.outputs.version-nightly }}
      version-nightly-extended: ${{ steps.changelog.outputs.version-nightly-extended }}
      version-nightly-extended-hash: ${{ steps.changelog.outputs.version-nightly-extended-hash }}
      version-nightly-hash: ${{ steps.changelog.outputs.version-nightly-hash }}
      version-patch: ${{ steps.changelog.outputs.version-patch }}
      version-patch-dev: ${{ steps.changelog.outputs.version-patch-dev }}
      version-patch-dev-hash: ${{ steps.changelog.outputs.version-patch-dev-hash }}
      version-patch-extended-dev: ${{ steps.changelog.outputs.version-patch-extended-dev }}
      version-patch-extended-dev-hash: ${{ steps.changelog.outputs.version-patch-extended-dev-hash }}
      version-patch-extended-nightly: ${{ steps.changelog.outputs.version-patch-extended-nightly }}
      version-patch-extended-nightly-hash: ${{ steps.changelog.outputs.version-patch-extended-nightly-hash }}
      version-patch-hash: ${{ steps.changelog.outputs.version-patch-hash }}
      version-patch-nightly: ${{ steps.changelog.outputs.version-patch-nightly }}
      version-patch-nightly-hash: ${{ steps.changelog.outputs.version-patch-nightly-hash }}
      version-root: ${{ steps.changelog.outputs.version-root }}
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
          sparse-checkout: package.json
          sparse-checkout-cone-mode: false

      - id: version
        name: Extract current version
        run: echo "root-version=$(jq --raw-output '.version' package.json)" >> $GITHUB_OUTPUT

      - id: changelog
        name: Generate changelog
        uses: oliversalzburg/action-automatic-semantic-releases@main
        with:
          automatic-release-tag: ${{ inputs.automatic-release-tag }}
          changelog-artifact: changelog.json
          dry-run: true
          publish: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          root-version: ${{ steps.version.outputs.root-version }}

      - name: Store Changelog
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: changelog.json
          path: changelog.json
          retention-days: 1

      - name: Show change counts
        env:
          MAJOR: ${{ steps.changelog.outputs.major-total }}
          MINOR: ${{ steps.changelog.outputs.minor-total }}
          PATCH: ${{ steps.changelog.outputs.patch-total }}
          LIFECYCLE: ${{ steps.changelog.outputs.lifecycle-total }}
        run: |
          echo Major changes: $MAJOR
          echo Minor changes: $MINOR
          echo Patch changes: $PATCH
          echo Lifecycle changes: $LIFECYCLE
