name: Publish mkdocs

on:
  workflow_call:
    inputs:
      dist-tag:
        description: The dist-tag to apply to the published npm package. If none is given, "latest" or "dev" are used depending on your `is-canary` setting.
        required: false
        type: string
      is-canary:
        default: true
        description: "DEPRECATED: Use `dist-tag` instead."
        required: false
        type: boolean
      output-artifact:
        default: output-artifact
        description: Name of the artifact that will contain the build output.
        required: false
        type: string
      output-path:
        default: ''
        description: A file, directory or wildcard pattern that describes the location of build output.
        required: false
        type: string
      publish-script:
        default: make
        description: Shell code to run to prepare the package for publishing.
        required: false
        type: string
      registry-url:
        default: https://registry.npmjs.org
        description: npm package registry URL to publish to.
        required: false
        type: string
      version:
        description: The version to publish.
        required: true
        type: string
    outputs:
      publish-url:
        description: The registry URL where the package version was published.
        value: ${{ jobs.publish.outputs.publish-url }}
    secrets:
      NPM_TOKEN:
        description: A personal access token to publish the package with.
        required: true

concurrency:
  group: publish-npm
  cancel-in-progress: false

env:
  NPM_DIST_TAG: ${{ inputs.dist-tag || ( inputs.is-canary && 'dev' || 'latest' ) }}
  # renovate: datasource=python-version depName=python versioning=python
  PYTHON_VERSION: "3.13.2"

jobs:
  publish:
    if: inputs.version != ''
    name: Publish
    outputs:
      publish-url: ${{ steps.details.outputs.publish-url }}
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: read
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Select Node.js version
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ inputs.registry-url }}

      - name: Enable Corepack
        run: |
          corepack enable
          yarn config set enableGlobalCache false

      - name: Load cached dependencies
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.NODE_VERSION }}

      - id: details
        name: Set package details
        run: |
          PACKAGE_NAME=$(jq --raw-output .name package.json)
          echo "PACKAGE_NAME=$PACKAGE_NAME" | tee $GITHUB_ENV
          
          DIST_URL=https://www.npmjs.com/package/$PACKAGE_NAME/v/${{ inputs.dist-tag }}
          echo "dist-url=$DIST_URL" >> $GITHUB_OUTPUT

          PUBLISH_URL=https://www.npmjs.com/package/$PACKAGE_NAME/v/${{ inputs.version }}
          echo "PUBLISH_URL=$PUBLISH_URL" | tee $GITHUB_ENV
          echo "publish-url=$PUBLISH_URL" >> $GITHUB_OUTPUT

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          ${{ inputs.publish-script }}
          npm --allow-same-version --ignore-scripts --no-git-tag-version version ${{ inputs.version }}
          npm publish --access=public --provenance --tag=${{ inputs.dist-tag }}
          echo "Published npm package to <${{ steps.details.outputs.publish-url }}>" >> $GITHUB_STEP_SUMMARY
          echo "Tagged npm package as <${{ steps.details.outputs.dist-url }}>" >> $GITHUB_STEP_SUMMARY

      - if: inputs.output-path != ''
        name: Upload output artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: ${{ inputs.output-artifact }}
          path: ${{ inputs.output-path }}
          retention-days: 1

      - continue-on-error: true
        name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
