name: Publish

on:
  workflow_call:

concurrency:
  group: docs-deploy
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3