name: QA

on:
  workflow_call:

env:
  # renovate: datasource=node-version depName=node versioning=node
  NODE_VERSION: "22.15.1"

jobs:
  qa:
    name: AWS Lambda Node.js
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Select Node.js version
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: |
          npm install --global corepack
          yarn config set enableGlobalCache false

      - name: Load cached dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.NODE_VERSION }}

      - name: Build, lint, test
        run: |
          make lint
          make build test
