name: QA

on:
  workflow_call:

env:
  # renovate: datasource=node-version depName=node versioning=node
  NODE_VERSION: "22.18.0"

jobs:
  qa:
    name: AWS Lambda Node.js
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          persist-credentials: false

      - name: Select Node.js version
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Load cached dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node{{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node${{ env.NODE_VERSION }}

      - name: Build, lint, test
        run: |
          make lint
          make build test
