name: QA

on:
  workflow_call:

env:
  # renovate: datasource=node-version depName=node versioning=node
  NODE_VERSION: "24.15.0"

jobs:
  qa:
    name: GitHub Action Node.js
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Select Node.js version
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Load cached dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node{{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node${{ env.NODE_VERSION }}

      - name: Build, lint, test
        run: |
          make lint
          make build test
