name: QA Internal

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frag-publish-mkdocs:
    permissions:
      contents: write
    uses: ./.github/workflows/frag-publish-mkdocs.yml
    with:
      working-directory: test
  frag-qa-mkdocs:
    permissions:
      contents: read
    uses: ./.github/workflows/frag-qa-mkdocs.yml
    with:
      working-directory: test
  qa-browser-app:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/qa-browser-app.yml
    with:
      working-directory: test
  qa-nodejs-oci:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/qa-nodejs-oci.yml
    with:
      containerfile: Containerfile
      context: test
      working-directory: test

  qa-passed-internal:
    name: QA Passed Internal
    needs:
      - frag-publish-mkdocs
      - frag-qa-mkdocs
      - qa-browser-app
      - qa-nodejs-oci
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
      - name: Success
        if: ${{ success() && !(contains(needs.*.result, 'failure')) }}
        run: exit 0
